name: CI-Textbit

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-[a-zA-Z0-9]*'
      - 'v[0-9]+.[0-9]+.[0-9]+'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build and publish Github package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: https://npm.pkg.github.com/

      - name: Install npm modules and build
        run: |-
          npm i
          npm run build
          npm prune --production

      - name: Publish package
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
